name: test
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [
          "openjdk@1.11.0-2",
          "openjdk@1.17.0"
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java_version }}
      - name: Test and coverage
        run: sbt clean coverage +test; sbt coverageReport
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: scoverage-report
          path: target/scala-2.13/scoverage-report
